#!/bin/bash

function main {
  while [[ $# -gt 0 ]];
  do
    case $1 in
    -y | --yes )
      SPARK="-auto-approve"
    ;;
    -t | --tld )
      shift
      QUAKE_TLD=$1
    esac
    shift
  done
  }
  TF_STATE_PATH=${REPO_ROOT}/state/tf/${QUAKE_TLD}.tfstate

  pushd ${REPO_ROOT}/terraform
    echo -e "running\nterraform init --backend-config=\"path=${TF_STATE_PATH}\""
    terraform init --backend-config="path=${TF_STATE_PATH}" &> /dev/null
    echo -e "running\nterraform desctroy ${SPARK}"
    terraform destroy ${SPARK}
  pop 

