#!/bin/bash
export REPO_ROOT="$(git rev-parse --show-toplevel)"
source ${REPO_ROOT}/.envrc

if [[ -z ${QUAKE_TLD} ]]; then
  echo "Please provide the QUAKE_TLD Environment Variable before running the script or provide QUAKE_TLD in ${REPO_ROOT}/configs/settings.rc"
  exit 1
fi

while [[ $# -gt 0 ]];
do
  case $1 in
  -w | --workflow )
    source $REPO_ROOT/installers/subcommands/workflow
    main "${@}"
  ;;
  -i | --install )
    source $REPO_ROOT/installers/subcommands/cli-install
    main
  ;;
  -b | --bootstrap)
    source $REPO_ROOT/installers/subcommands/bootstrap
    main
  ;;
  -p | --purge)
    source $REPO_ROOT/installers/subcommands/purge
    main "${@}"
  ;;
  -t | --template-apps)
    source $REPO_ROOT/installers/subcommands/template
    shift
    main "${@}"
  ;;
  -d | --deploy)
    shift
    source $REPO_ROOT/installers/subcommands/deploy
    main "${@}"
    break;
  ;;
  -D | --delete )
    shift
    source $REPO_ROOT/installers/subcommands/boom
    main "${@}"
  ;;
  -l | --loadout )
    shift
    source $REPO_ROOT/installers/subcommands/loadout
    main "${@}"
  ;;
  *)
    echo "unknown subcommand or parameter $1"
    exit 1
  ;;
  esac
  shift
done


